### ISSUE TITLE
bluetooth doesn't work

### ISSUE THREAD

**Issue by PeppinoTech** [RaphProductions/macOS-t460#5]
https://github.com/RaphProductions/macOS-t460/assets/135860662/f7e44174-bc9e-4412-9109-8416754982f2

you see it here

**Comment by PeppinoTech** [comment]
here's the log for bluetoothd

`-------------------------------------
Translated Report (Full Report Below)
-------------------------------------

Process:               bluetoothd [143]
Path:                  /usr/sbin/bluetoothd
Identifier:            bluetoothd
Version:               ???
Code Type:             X86-64 (Native)
Parent Process:        launchd [1]
User ID:               0

Date/Time:             2024-05-17 14:29:24.6706 +0300
OS Version:            macOS 13.6.7 (22G720)
Report Version:        12
Anonymous UUID:        FDAEA471-6D0E-30EA-128B-0EAD1B2E8F29


Time Awake Since Boot: 29 seconds

System Integrity Protection: enabled

Crashed Thread:        1

Exception Type:        EXC_GUARD
Exception Codes:       GUARD_TYPE_USER
Exception Codes:       0x6000000000000012, 0x0000000000000002

Termination Reason:    Namespace LIBSYSTEM, Code 2 Application Triggered Fault

Thread 0:
0   libsystem_kernel.dylib        	    0x7ff814da9552 mach_msg2_trap + 10
1   libsystem_kernel.dylib        	    0x7ff814db76cd mach_msg2_internal + 78
2   libsystem_kernel.dylib        	    0x7ff814db0584 mach_msg_overwrite + 692
3   libsystem_kernel.dylib        	    0x7ff814da983a mach_msg + 19
4   CoreFoundation                	    0x7ff814ec3fef __CFRunLoopServiceMachPort + 145
5   CoreFoundation                	    0x7ff814ec2a70 __CFRunLoopRun + 1365
6   CoreFoundation                	    0x7ff814ec1eb1 CFRunLoopRunSpecific + 560
7   CoreFoundation                	    0x7ff814f455d5 CFRunLoopRun + 40
8   bluetoothd                    	       0x10d0b68df 0x10d08d000 + 170207
9   dyld                          	    0x7ff814a8d41f start + 1903

Thread 1 Crashed:
0   libsystem_kernel.dylib        	    0x7ff814db49fa os_fault_with_payload + 10
1   bluetoothd                    	       0x10d175c98 0x10d08d000 + 953496
2   bluetoothd                    	       0x10d11eae3 0x10d08d000 + 596707
3   bluetoothd                    	       0x10d45165f 0x10d08d000 + 3950175
4   bluetoothd                    	       0x10d452a57 0x10d08d000 + 3955287
5   bluetoothd                    	       0x10d430d09 0x10d08d000 + 3816713
6   bluetoothd                    	       0x10d430933 0x10d08d000 + 3815731
7   libdispatch.dylib             	    0x7ff814c45d91 _dispatch_call_block_and_release + 12
8   libdispatch.dylib             	    0x7ff814c47033 _dispatch_client_callout + 8
9   libdispatch.dylib             	    0x7ff814c4d200 _dispatch_lane_serial_drain + 769
10  libdispatch.dylib             	    0x7ff814c4dd6c _dispatch_lane_invoke + 417
11  libdispatch.dylib             	    0x7ff814c583fc _dispatch_workloop_worker_thread + 765
12  libsystem_pthread.dylib       	    0x7ff814de4c55 _pthread_wqthread + 327
13  libsystem_pthread.dylib       	    0x7ff814de3bbf start_wqthread + 15

Thread 2:
0   libsystem_kernel.dylib        	    0x7ff814daac3e __workq_kernreturn + 10
1   libsystem_pthread.dylib       	    0x7ff814de4cb9 _pthread_wqthread + 427
2   libsystem_pthread.dylib       	    0x7ff814de3bbf start_wqthread + 15

Thread 3:
0   libsystem_kernel.dylib        	    0x7ff814daac3e __workq_kernreturn + 10
1   libsystem_pthread.dylib       	    0x7ff814de4cb9 _pthread_wqthread + 427
2   libsystem_pthread.dylib       	    0x7ff814de3bbf start_wqthread + 15

Thread 4:: StackLoop
0   libsystem_kernel.dylib        	    0x7ff814dac08e __psynch_cvwait + 10
1   libsystem_pthread.dylib       	    0x7ff814de878d _pthread_cond_wait + 1295
2   bluetoothd                    	       0x10d11ed9c 0x10d08d000 + 597404
3   libsystem_pthread.dylib       	    0x7ff814de81d3 _pthread_start + 125
4   libsystem_pthread.dylib       	    0x7ff814de3bd3 thread_start + 15

Thread 5:
0   libsystem_kernel.dylib        	    0x7ff814daac3e __workq_kernreturn + 10
1   libsystem_pthread.dylib       	    0x7ff814de4cb9 _pthread_wqthread + 427
2   libsystem_pthread.dylib       	    0x7ff814de3bbf start_wqthread + 15


Thread 1 crashed with X86 Thread State (64-bit):
  rax: 0x0000000002000211  rbx: 0x0000000000000072  rcx: 0x000070000a283508  rdx: 0x000070000a283510
  rdi: 0x0000000000000012  rsi: 0x0000000000000002  rbp: 0x000070000a2835a0  rsp: 0x000070000a283508
   r8: 0x00007f858c92aae0   r9: 0x0000000000000000  r10: 0x000000000000004a  r11: 0x0000000000000246
  r12: 0x000070000a283560  r13: 0x0000000000000004  r14: 0x000000000000004a  r15: 0x000070000a283510
  rip: 0x00007ff814db49fa  rfl: 0x0000000000000246  cr2: 0x0000000000000000
  
Logical CPU:     0
Error Code:      0x02000211 
Trap Number:     133


Binary Images:
       0x10d08d000 -        0x10d878fff bluetoothd (*) <5c79a494-63f1-311a-b49a-b14d8c0b9500> /usr/sbin/bluetoothd
       0x10dbb3000 -        0x10dc3efff libAWDProtobufBluetooth.dylib (*) <9b64d46f-bbb9-37a0-9157-93beb2e8127c> /System/Library/PrivateFrameworks/WirelessDiagnostics.framework/Versions/A/Libraries/libAWDProtobufBluetooth.dylib
       0x10db54000 -        0x10db5ffff com.apple.iokit.IOUSBLib (900.4.2) <86b84a32-d80e-33e1-8232-78050a95cf79> /System/Library/Extensions/IOUSBHostFamily.kext/Contents/PlugIns/IOUSBLib.bundle/Contents/MacOS/IOUSBLib
    0x7ff814da8000 -     0x7ff814de1fff libsystem_kernel.dylib (*) <e82b6d50-ac03-370d-a74d-eb1a2725b6c5> /usr/lib/system/libsystem_kernel.dylib
    0x7ff814e47000 -     0x7ff8152e3fef com.apple.CoreFoundation (6.9) <3435a4a4-d0f8-3399-b0ad-49c3635a0f61> /System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation
    0x7ff814a87000 -     0x7ff814b1f5ef dyld (*) <2faf54fd-58e6-360c-9bd8-2fbfe8be93d3> /usr/lib/dyld
    0x7ff814c44000 -     0x7ff814c8bff3 libdispatch.dylib (*) <9e8b726d-ca70-32d6-8987-0fa21014ec5b> /usr/lib/system/libdispatch.dylib
    0x7ff814de2000 -     0x7ff814dedfff libsystem_pthread.dylib (*) <60b15e1f-39ea-33a1-8616-3af57dc1094a> /usr/lib/system/libsystem_pthread.dylib

External Modification Summary:
  Calls made by other processes targeting this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by all processes on this machine:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0

VM Region Summary:
ReadOnly portion of Libraries: Total=582.1M resident=0K(0%) swapped_out_or_unallocated=582.1M(100%)
Writable regions: Total=87.6M written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=87.6M(100%)

                                VIRTUAL   REGION 
REGION TYPE                        SIZE    COUNT (non-coalesced) 
===========                     =======  ======= 
Activity Tracing                   256K        1 
Dispatch continuations            32.0M        1 
IOKit                               16K        2 
Kernel Alloc Once                    8K        1 
MALLOC                            44.4M       21 
MALLOC guard page                   32K        8 
SQLite page cache                  256K        2 
STACK GUARD                       56.0M        6 
Stack                             10.5M        7 
VM_ALLOCATE                         32K        3 
__CTF                               824        1 
__DATA                            21.0M      472 
__DATA_CONST                      27.1M      308 
__DATA_DIRTY                      1343K      180 
__FONT_DATA                        2352        1 
__INFO_FILTER                         8        1 
__LINKEDIT                       171.8M        5 
__OBJC_RO                         66.3M        1 
__OBJC_RW                         2013K        2 
__TEXT                           410.3M      493 
dyld private memory                260K        2 
mapped file                       29.5M        8 
shared memory                      588K        7 
===========                     =======  ======= 
TOTAL                            873.7M     1533 



-----------
Full Report
-----------

{"is_simulated":1,"app_name":"bluetoothd","timestamp":"2024-05-17 14:29:34.00 +0300","app_version":"","slice_uuid":"5c79a494-63f1-311a-b49a-b14d8c0b9500","build_version":"","platform":1,"share_with_app_devs":0,"is_first_party":1,"bug_type":"309","os_version":"macOS 13.6.7 (22G720)","roots_installed":0,"incident_id":"777D5324-2F68-488D-8550-07D323CCD2D1","name":"bluetoothd"}
{
  "uptime" : 29,
  "procRole" : "Unspecified",
  "version" : 2,
  "userID" : 0,
  "deployVersion" : 210,
  "modelCode" : "MacBookPro16,3",
  "coalitionID" : 129,
  "osVersion" : {
    "train" : "macOS 13.6.7",
    "build" : "22G720",
    "releaseType" : "User"
  },
  "captureTime" : "2024-05-17 14:29:24.6706 +0300",
  "incident" : "777D5324-2F68-488D-8550-07D323CCD2D1",
  "pid" : 143,
  "cpuType" : "X86-64",
  "roots_installed" : 0,
  "bug_type" : "309",
  "procLaunch" : "2024-05-17 14:28:57.1338 +0300",
  "procStartAbsTime" : 3159312348,
  "procName" : "bluetoothd",
  "procPath" : "\/usr\/sbin\/bluetoothd",
  "parentProc" : "launchd",
  "parentPid" : 1,
  "coalitionName" : "com.apple.bluetoothd",
  "crashReporterKey" : "FDAEA471-6D0E-30EA-128B-0EAD1B2E8F29",
  "throttleTimeout" : 10,
  "codeSigningID" : "com.apple.bluetoothd",
  "codeSigningTeamID" : "",
  "codeSigningFlags" : 570522385,
  "codeSigningValidationCategory" : 1,
  "codeSigningTrustLevel" : 0,
  "sip" : "enabled",
  "isSimulated" : 1,
  "exception" : {"codes":"0x6000000000000012, 0x0000000000000002","reason":2,"message":"namespc 18 reason_code 0x0000000000000002","subtype":"GUARD_TYPE_USER","type":"EXC_GUARD","rawCodes":[6917529027641081874,2],"namespc":18},
  "termination" : {"flags":518,"code":2,"namespace":"LIBSYSTEM","indicator":"Application Triggered Fault"},
  "extMods" : {"caller":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"system":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"targeted":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"warnings":0},
  "faultingThread" : 1,
  "threads" : [{"id":2290,"frames":[{"imageOffset":5458,"symbol":"mach_msg2_trap","symbolLocation":10,"imageIndex":3},{"imageOffset":63181,"symbol":"mach_msg2_internal","symbolLocation":78,"imageIndex":3},{"imageOffset":34180,"symbol":"mach_msg_overwrite","symbolLocation":692,"imageIndex":3},{"imageOffset":6202,"symbol":"mach_msg","symbolLocation":19,"imageIndex":3},{"imageOffset":511983,"symbol":"__CFRunLoopServiceMachPort","symbolLocation":145,"imageIndex":4},{"imageOffset":506480,"symbol":"__CFRunLoopRun","symbolLocation":1365,"imageIndex":4},{"imageOffset":503473,"symbol":"CFRunLoopRunSpecific","symbolLocation":560,"imageIndex":4},{"imageOffset":1041877,"symbol":"CFRunLoopRun","symbolLocation":40,"imageIndex":4},{"imageOffset":170207,"imageIndex":0},{"imageOffset":25631,"symbol":"start","symbolLocation":1903,"imageIndex":5}]},{"triggered":true,"id":2291,"threadState":{"r13":{"value":4},"rax":{"value":33554961},"rflags":{"value":582},"cpu":{"value":0},"r14":{"value":74},"rsi":{"value":2},"r8":{"value":140211565800160},"cr2":{"value":0},"rdx":{"value":123145472718096},"r10":{"value":74},"r9":{"value":0},"r15":{"value":123145472718096},"rbx":{"value":114},"trap":{"value":133},"err":{"value":33554961},"r11":{"value":582},"rip":{"value":140703478532602,"matchesCrashFrame":1},"rbp":{"value":123145472718240},"rsp":{"value":123145472718088},"r12":{"value":123145472718176},"rcx":{"value":123145472718088},"flavor":"x86_THREAD_STATE","rdi":{"value":18}},"frames":[{"imageOffset":51706,"symbol":"os_fault_with_payload","symbolLocation":10,"imageIndex":3},{"imageOffset":953496,"imageIndex":0},{"imageOffset":596707,"imageIndex":0},{"imageOffset":3950175,"imageIndex":0},{"imageOffset":3955287,"imageIndex":0},{"imageOffset":3816713,"imageIndex":0},{"imageOffset":3815731,"imageIndex":0},{"imageOffset":7569,"symbol":"_dispatch_call_block_and_release","symbolLocation":12,"imageIndex":6},{"imageOffset":12339,"symbol":"_dispatch_client_callout","symbolLocation":8,"imageIndex":6},{"imageOffset":37376,"symbol":"_dispatch_lane_serial_drain","symbolLocation":769,"imageIndex":6},{"imageOffset":40300,"symbol":"_dispatch_lane_invoke","symbolLocation":417,"imageIndex":6},{"imageOffset":82940,"symbol":"_dispatch_workloop_worker_thread","symbolLocation":765,"imageIndex":6},{"imageOffset":11349,"symbol":"_pthread_wqthread","symbolLocation":327,"imageIndex":7},{"imageOffset":7103,"symbol":"start_wqthread","symbolLocation":15,"imageIndex":7}]},{"id":2292,"frames":[{"imageOffset":11326,"symbol":"__workq_kernreturn","symbolLocation":10,"imageIndex":3},{"imageOffset":11449,"symbol":"_pthread_wqthread","symbolLocation":427,"imageIndex":7},{"imageOffset":7103,"symbol":"start_wqthread","symbolLocation":15,"imageIndex":7}]},{"id":2293,"frames":[{"imageOffset":11326,"symbol":"__workq_kernreturn","symbolLocation":10,"imageIndex":3},{"imageOffset":11449,"symbol":"_pthread_wqthread","symbolLocation":427,"imageIndex":7},{"imageOffset":7103,"symbol":"start_wqthread","symbolLocation":15,"imageIndex":7}]},{"id":2294,"name":"StackLoop","frames":[{"imageOffset":16526,"symbol":"__psynch_cvwait","symbolLocation":10,"imageIndex":3},{"imageOffset":26509,"symbol":"_pthread_cond_wait","symbolLocation":1295,"imageIndex":7},{"imageOffset":597404,"imageIndex":0},{"imageOffset":25043,"symbol":"_pthread_start","symbolLocation":125,"imageIndex":7},{"imageOffset":7123,"symbol":"thread_start","symbolLocation":15,"imageIndex":7}]},{"id":2295,"frames":[{"imageOffset":11326,"symbol":"__workq_kernreturn","symbolLocation":10,"imageIndex":3},{"imageOffset":11449,"symbol":"_pthread_wqthread","symbolLocation":427,"imageIndex":7},{"imageOffset":7103,"symbol":"start_wqthread","symbolLocation":15,"imageIndex":7}]}],
  "usedImages" : [
  {
    "source" : "P",
    "arch" : "x86_64",
    "base" : 4513648640,
    "size" : 8306688,
    "uuid" : "5c79a494-63f1-311a-b49a-b14d8c0b9500",
    "path" : "\/usr\/sbin\/bluetoothd",
    "name" : "bluetoothd"
  },
  {
    "source" : "P",
    "arch" : "x86_64",
    "base" : 4525338624,
    "size" : 573440,
    "uuid" : "9b64d46f-bbb9-37a0-9157-93beb2e8127c",
    "path" : "\/System\/Library\/PrivateFrameworks\/WirelessDiagnostics.framework\/Versions\/A\/Libraries\/libAWDProtobufBluetooth.dylib",
    "name" : "libAWDProtobufBluetooth.dylib"
  },
  {
    "source" : "P",
    "arch" : "x86_64",
    "base" : 4524949504,
    "CFBundleShortVersionString" : "900.4.2",
    "CFBundleIdentifier" : "com.apple.iokit.IOUSBLib",
    "size" : 49152,
    "uuid" : "86b84a32-d80e-33e1-8232-78050a95cf79",
    "path" : "\/System\/Library\/Extensions\/IOUSBHostFamily.kext\/Contents\/PlugIns\/IOUSBLib.bundle\/Contents\/MacOS\/IOUSBLib",
    "name" : "IOUSBLib",
    "CFBundleVersion" : "900.4.2"
  },
  {
    "source" : "P",
    "arch" : "x86_64",
    "base" : 140703478480896,
    "size" : 237568,
    "uuid" : "e82b6d50-ac03-370d-a74d-eb1a2725b6c5",
    "path" : "\/usr\/lib\/system\/libsystem_kernel.dylib",
    "name" : "libsystem_kernel.dylib"
  },
  {
    "source" : "P",
    "arch" : "x86_64h",
    "base" : 140703479132160,
    "CFBundleShortVersionString" : "6.9",
    "CFBundleIdentifier" : "com.apple.CoreFoundation",
    "size" : 4837360,
    "uuid" : "3435a4a4-d0f8-3399-b0ad-49c3635a0f61",
    "path" : "\/System\/Library\/Frameworks\/CoreFoundation.framework\/Versions\/A\/CoreFoundation",
    "name" : "CoreFoundation",
    "CFBundleVersion" : "1979.104"
  },
  {
    "source" : "P",
    "arch" : "x86_64",
    "base" : 140703475200000,
    "size" : 624112,
    "uuid" : "2faf54fd-58e6-360c-9bd8-2fbfe8be93d3",
    "path" : "\/usr\/lib\/dyld",
    "name" : "dyld"
  },
  {
    "source" : "P",
    "arch" : "x86_64",
    "base" : 140703477022720,
    "size" : 294900,
    "uuid" : "9e8b726d-ca70-32d6-8987-0fa21014ec5b",
    "path" : "\/usr\/lib\/system\/libdispatch.dylib",
    "name" : "libdispatch.dylib"
  },
  {
    "source" : "P",
    "arch" : "x86_64",
    "base" : 140703478718464,
    "size" : 49152,
    "uuid" : "60b15e1f-39ea-33a1-8616-3af57dc1094a",
    "path" : "\/usr\/lib\/system\/libsystem_pthread.dylib",
    "name" : "libsystem_pthread.dylib"
  }
],
  "sharedCache" : {
  "base" : 140703474577408,
  "size" : 21474836480,
  "uuid" : "5b024447-21cb-39dc-9946-0924a6000a4b"
},
  "vmSummary" : "ReadOnly portion of Libraries: Total=582.1M resident=0K(0%) swapped_out_or_unallocated=582.1M(100%)\nWritable regions: Total=87.6M written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=87.6M(100%)\n\n                                VIRTUAL   REGION \nREGION TYPE                        SIZE    COUNT (non-coalesced) \n===========                     =======  ======= \nActivity Tracing                   256K        1 \nDispatch continuations            32.0M        1 \nIOKit                               16K        2 \nKernel Alloc Once                    8K        1 \nMALLOC                            44.4M       21 \nMALLOC guard page                   32K        8 \nSQLite page cache                  256K        2 \nSTACK GUARD                       56.0M        6 \nStack                             10.5M        7 \nVM_ALLOCATE                         32K        3 \n__CTF                               824        1 \n__DATA                            21.0M      472 \n__DATA_CONST                      27.1M      308 \n__DATA_DIRTY                      1343K      180 \n__FONT_DATA                        2352        1 \n__INFO_FILTER                         8        1 \n__LINKEDIT                       171.8M        5 \n__OBJC_RO                         66.3M        1 \n__OBJC_RW                         2013K        2 \n__TEXT                           410.3M      493 \ndyld private memory                260K        2 \nmapped file                       29.5M        8 \nshared memory                      588K        7 \n===========                     =======  ======= \nTOTAL                            873.7M     1533 \n",
  "legacyInfo" : {
  "threadTriggered" : {

  }
},
  "logWritingSignature" : "d984c7293254fcff233a20baa761646a532ed471"
}

`

**Comment by PeppinoTech** [comment]
@RaphProductions

**Comment by PeppinoTech** [comment]
fixed by deleting intelbtinjector

**Comment by RaphProductions** [comment]
Sorry for inactivity on this repo. I will release a new version fixing Bluetooth according to what you said.

**Comment by RaphProductions** [comment]
Update: What do you mean by "IntelBTInjector"? There's no "IntelBTInjector" kext.

**Comment by PeppinoTech** [comment]
> Update: What do you mean by "IntelBTInjector"? There's no "IntelBTInjector" kext.

Sorry for late reply, but on Monterey and higher versions The "intelBTInjector" must be deleted. So I recommend to make 2 files. Like the first is EFI bigsur and the second is EFI Monterey and higher. 

this is it.
-Mark
@RaphProductions

**Comment by PeppinoTech** [comment]
> Update: What do you mean by "IntelBTInjector"? There's no "IntelBTInjector" kext.

There is a btinjector bro
